config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :assignments
  resources :physicians
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :patient
  belongs_to :physician
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    redirect_to edit_assignment_path(@assignment)
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:patient_id,
                                                       :referring_physician_id,
                                                       :primary_care_physician_id,
                                                       :pharmacy_name)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= simple_form_for(@assignment , :html => {class:'form-horizontal' }) do |f| %>
  <div class="row">
    <div class="col-md-4">
      <h2 style="margin-top: 0px;"><%= @assignment.persisted? ? "Edit " : "New assignment" %></h2>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <hr class="slim">
  <div class='row'>
    <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this @assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class='col-md-9 col-md-offset-2'>
      <div class="form-inputs">

          <div class="col-md-3 form-group">Patient</div>
          <div class="col-md-9 form-group">
                  <%= f.collection_select :patient_id, Patient.all, :id,:name, {},{:class=>"form-control selectpicker cardsection_selector"} %>
          </div>

          <div class="col-md-3 form-group">Referring Physician</div>
          <div class="col-md-9 form-group">
                  <%= f.collection_select :referring_physician_id, Physician.all, :id,:name, {},{:class=>"form-control selectpicker cardsection_selector"} %>
          </div>

          <div class="col-md-3 form-group">Primary Care Physician</div>
          <div class="col-md-9 form-group">
                  <%= f.collection_select :primary_care_physician_id, Physician.all, :id,:name, {},{:class=>"form-control selectpicker cardsection_selector"} %>
          </div>

          <div class="col-md-3 form-group">Pharmacy Name</div>
          <div class="col-md-9 form-group">
                  <%= f.text_field :pharmacy_name, :class=>"form-control "%>
          </div>

      </div>

      </div>
    </div>
  <hr class="slim">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Back', assignments_path, class:'btn btn-default' %>
      <%= f.button :submit, class:'btn btn-default pull-right' %>
    </div>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <li><%= link_to "Assignments", assignments_path %></li>
  <li><%= link_to @assignment.id, edit_assignment_path(@assignment) %></li>
  <li class="active">Edit</li>
</ol>
<%= render 'form' %>

app/views/assignments/index.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <!-- <li><%#= link_to "Home", root_path %></li> -->
  <li class='active'>Assignments</li>
</ol>
<div class="row">
  <div class="col-md-4">
    <h2 style="margin-top: 25px;text-align: center;">Assignments</h2>
  </div>
  <div class="col-md-8">
    <%= link_to 'Add', new_assignment_path, class: "btn btn-default pull-right" %>
  </div>
</div>
<hr class="slim">
<hr class="slim">
<!-- Table -->
<table class="table">
  <thead>
  <tr>
    <th>Patient Name</th>
    <th>Referring Physician</th>
    <th>Primary Care Physician</th>
    <th>Pharmacy Name</th>
    <th class="col-md-1"></th>
  </tr>
  </thead>
  <tbody>
  <% @assignments.each do |assignment| %>
      <tr>
        <td><%= Patient.where(:id => assignment.patient_id).name %></td>
        <td><%= Physician.where(:id => assignment.referring_physician_id).name %></td>
        <td><%= Physician.where(:id => assignment.primary_care_physician_id).name %></td>
        <td><%= assignment.pharmacy_name %></td>
        <td class="col-md-1 text-right">
          <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_assignment_path(assignment) %>
          <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, assignment, method: :delete,
                      data: {title: 'Delete Assignment?', confirm: "Are you sure you want to delete Assignment ?"},
                      class: "text-danger" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/assignments/new.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <li><%= link_to "Assignments", assignments_path %></li>
  <li class="active">New</li>
</ol>
<%= render 'form' %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>