config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :assignments
  resources :physicians
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :assignments
  has_many :patients, through: :assignments
  has_many :physician_addresses
  has_many :addresses, through: :physician_addresses


  accepts_nested_attributes_for :addresses
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, only: [:show, :edit, :update, :destroy]

  # GET /physicians
  # GET /physicians.json
  def index
    @physicians = Physician.all
  end

  # GET /physicians/1
  # GET /physicians/1.json
  def show
    redirect_to edit_physician_path(@physician)
  end

  # GET /physicians/new
  def new
    @physician = Physician.new
  end

  # GET /physicians/1/edit
  def edit
  end

  # POST /physicians
  # POST /physicians.json
  def create
    @physician = Physician.new(physician_params)

    respond_to do |format|
      if @physician.save
        format.html { redirect_to @physician, notice: 'Physician was successfully created.' }
        format.json { render :show, status: :created, location: @physician }
      else
        format.html { render :new }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /physicians/1
  # PATCH/PUT /physicians/1.json
  def update
    respond_to do |format|
      if @physician.update(physician_params)
        format.html { redirect_to @physician, notice: 'Physician was successfully updated.' }
        format.json { render :show, status: :ok, location: @physician }
      else
        format.html { render :edit }
        format.json { render json: @physician.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /physicians/1
  # DELETE /physicians/1.json
  def destroy
    @physician.destroy
    respond_to do |format|
      format.html { redirect_to physicians_url, notice: 'Physician was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_physician
      @physician = Physician.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def physician_params
      params.require(:physician).permit(:name,
                                                       :speciality,
                                                       :gender,
                                                       :age,
                                                       :nationality,
                                                       :mobile_number,
                                                       :email_id,
                                                       :marital_status,
                                                       :blood_group,
                                                       addresses_attributes: [:id,
                                                                                            :address_for,
                                                                                            :flat_number,
                                                                                            :street_name,
                                                                                            :area,
                                                                                            :city,
                                                                                            :state,
                                                                                            :done,
                                                                                            :_destroy])
    end
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/physicians/_address_fields.html.erb
<div class="nested-fields" style="  border: 1px solid #ccc;padding: 10px;margin-top: 12px;border-radius: 4px;">
<h4 style="border-bottom:1px solid #03C9A9; padding-bottom:8px;">Address<%= f.object.try(:address_for)%></h4>

  <div class="field form-group start_date_sib">
    <%= f.label :address_for, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :address_for,:class=>"form-control "%>
    </div>
  </div>

  <div class="field form-group start_date_sib">
    <%= f.label :flat_number, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :flat_number,:class=>"form-control "%>
    </div>
  </div>

  <div class="field form-group minimum_days_sib" style="">
    <%= f.label :street_name, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :street_name,:class=>"form-control " %>
    </div>
  </div>


  <div class="field form-group end_date_sib">
    <%= f.label :area, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :area,:class=>"form-control "%>
    </div>
  </div>

  <div class="field form-group multiple_date_sib">
    <%= f.label :city, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :city,:class=>"form-control "%>
    </div>
  </div>

  <div class="field form-group multiple_date_sib">
    <%= f.label :state, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :state,:class=>"form-control "%>
    </div>
  </div>

  <div class="field form-group multiple_date_sib">
    <%= f.label :pin_code, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
    <div class="col-sm-10">
    <%=f.text_field :pin_code,:class=>"form-control "%>
    </div>
  </div>



<%=link_to_remove_association "Remove Address", f%>

</div>

app/views/physicians/_form.html.erb
<%= simple_form_for(@physician , :html => {class:'form-horizontal' }) do |f| %>
  <div class="row">
    <div class="col-md-4">
      <h2 style="margin-top: 25px;text-align: center;"><%= @physician.persisted? ? "Edit " + @physician.name.to_s : "New Physician" %></h2>
    </div>
    <div class="col-md-8">
    </div>
  </div>
  <hr class="slim">
  <div class='row'>
    <% if @physician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@physician.errors.count, "error") %> prohibited this @physician from being saved:</h2>

      <ul>
      <% @physician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class='col-md-6 col-md-offset-3'>
      <div class="form-inputs">
        <div class="field form-group multiple_date_sib">
          <%= f.label :name, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :name,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :speciality, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :speciality,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :gender, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :gender,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :age, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.number_field :age,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :nationality, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :nationality,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :mobile_number, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :mobile_number,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :email_id, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.email_field :email_id,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :marital_status, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :marital_status,:class=>"form-control "%>
          </div>
        </div>

        <div class="field form-group multiple_date_sib">
          <%= f.label :blood_group, :class=>"col-sm-2 control-label", :style => "margin-top: 15px;" %><br>
          <div class="col-sm-10">
          <%=f.text_field :blood_group,:class=>"form-control "%>
          </div>
        </div>

        <div class="field">
          <div class="form-group">
             <%=f.fields_for :addresses, :required=>true do |address| %>
             <%=render 'address_fields', :f => address%>
             <%end%>
             <%=link_to_add_association 'Add Address', f, :addresses, :style=>"margin-top: 20px;color: #FFFFFF;", :class=>"btn btn-warning date-custom-btn"%>
          </div>
        </div>

      </div>
    </div>
  </div>
  <hr class="slim">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Back', physicians_path, class:'btn btn-default' %>
      <%= f.button :submit, class:'pull-right' %>
    </div>
  </div>
<% end %>

app/views/physicians/edit.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <li><%= link_to "Physicians", physicians_path %></li>
  <li><%= link_to @physician.id, edit_physician_path(@physician) %></li>
  <li class="active">Edit</li>
</ol>
<%= render 'form' %>

app/views/physicians/index.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <li class='active'>Physicians</li>
</ol>
<div class="row">
  <div class="col-md-4">
    <h2 style="margin-top: 25px;text-align: center;">Physicians</h2>
  </div>
  <div class="col-md-8">
    <%= link_to 'Add', new_physician_path, class: "btn btn-default pull-right" %>
  </div>
</div>
<hr class="slim">
<hr class="slim">
<!-- Table -->
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Speciality</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Nationality</th>
    <th>Mobile</th>
    <th>Email</th>
    <th>Marital Status</th>
    <th>Blood Group</th>
    <th class="col-md-1"></th>
  </tr>
  </thead>
  <tbody>
  <% @physicians.each do |physician| %>
      <tr>
        <td><%= link_to physician.name, edit_physician_path(physician) %></td>
        <td><%= physician.speciality %></td>
        <td><%= physician.gender %></td>
        <td><%= physician.age %></td>
        <td><%= physician.nationality %></td>
        <td><%= physician.mobile_number %></td>
        <td><%= physician.email_id %></td>
        <td><%= physician.marital_status %></td>
        <td><%= physician.blood_group%></td>
        <td class="col-md-1 text-right">
          <%= link_to '<span class="glyphicon glyphicon-edit"></span>'.html_safe, edit_physician_path(physician) %>
          <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, physician, method: :delete,
                      data: {title: 'Delete physician?', confirm: "Are you sure you want to delete physician #{physician.name}?"},
                      class: "text-danger" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/physicians/new.html.erb
<ol class="breadcrumb" style="margin-top: 70px">
  <li><%= link_to "Physician", physicians_path %></li>
  <li class="active">New</li>
</ol>
<%= render 'form' %>

app/views/physicians/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_physician_path(@physician) %> |
<%= link_to 'Back', physicians_path %>