config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :assignments
  resources :physicians
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-fixed-top navbar-default">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><%= link_to 'Patients'.html_safe, patients_path %>	</li>
						<li><%= link_to 'Physicians'.html_safe, physicians_path %></li>
						<li><%= link_to 'Assignments'.html_safe, assignments_path %></li>
					</ul>
			</div>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatientPhysician</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Wallet Buddy</title>
		<%= include_gon  %>
		<%= stylesheet_link_tag "admin", media: "all", "data-turbolinks-track" => false %>
		<!-- Include Editor style. -->
		<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.2/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
		<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.2/css/froala_style.min.css' rel='stylesheet' type='text/css' />

		<%= javascript_include_tag "admin", "data-turbolinks-track" => false %>
		<!-- Include JS file. -->
		<script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.4.2/js/froala_editor.min.js'></script>
		<script src="https://use.fontawesome.com/4534d7a2be.js"></script>
		<%= csrf_meta_tags %>
		<!-- Material Icons -->
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	</head>

	<body data-page="<%= admin_data_page_attributes %>" style="margin-top: 60px;">
		<%= render 'layouts/header' %>
		<div class="container" role="main">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</div>
	</body>
</html>